# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install pip3
  - sudo pip3 install pip3
  - sudo pip3 install music21

addons:
  apt:
    packages:
      - python3.7
      - lilypond
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal

language: R

cache:
  packages: true
