# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install pip3
  - sudo pip3 install pip3
  - sudo pip3 install music21

addons:
  apt:
    packages:
      - lilypond

language: R

cache:
  packages: true
