# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
before_install:
  - sudo pip install numpy music21

addons:
  apt:
    packages:
      - lilypond

language: R

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false


cache:
  packages: true
