# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
before_install:
  - sudo pip3 install music21

addons:
  apt:
    packages:
      - lilypond
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal

language: R

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - pip3 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - R CMD INSTALL .
